[package]
name = "fontloader"
version = "0.0.1"
edition = "2021"
authors = ["Mith@mmk"]
description = "A font loader for Rust"
license = "MIT"
repository = "https://github.com/mith-mmk/FontReader"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bin-rs = "0.0.9"
miniz_oxide = {version = "0.7.1"}
# byteorder = "1.4.3"
# iconv = "0.1"
num-traits = "0.2"
num-derive = "0.4"